blocks = {
    "1_natural_blocks": {
        "D": "minecraft:dirt",
        "G": "minecraft:grass_block",
        "S": "minecraft:stone",
        "g":"minecraft:granite",
        "ď": "minecraft:diorite",
        "ą": "minecraft:andesite",
        "s": "minecraft:sand",
        "Ğ": "minecraft:gravel",
        "c": "minecraft:clay",
        "I": "minecraft:ice",
        "P": "minecraft:packed_ice",
        "S": "minecraft:snow_block",
        "W": "minecraft:water",
        "L": "minecraft:lava",
        "p": "minecraft:podzol",
        "M": "minecraft:mycelium",
    },
    "2_ores": {
        "-": "minecraft:coal_ore",
        "-": "minecraft:iron_ore",
        "-": "minecraft:copper_ore",
        "-": "minecraft:gold_ore",
        "-": "minecraft:diamond_ore",
        "-": "minecraft:emerald_ore",
        "-": "minecraft:redstone_ore",
        "-": "minecraft:lapis_ore",
        "-": "minecraft:nether_quartz_ore",
        "-": "minecraft:ancient_debris",
    },
    "3_building_blocks": {
        "-": "minecraft:cobblestone",
        "-": "minecraft:stone_bricks",
        "-": "minecraft:oak_planks",
        "-": "minecraft:spruce_planks",
        "-": "minecraft:birch_planks",
        "-": "minecraft:jungle_planks",
        "-": "minecraft:acacia_planks",
        "-": "minecraft:dark_oak_planks",
        "-": "minecraft:mangrove_planks",
        "-": "minecraft:concrete", # (various_colors:_minecraft:white_concrete,_minecraft:black_concrete,_etc)
        "-": "minecraft:terracotta",
        "-": "minecraft:glazed_terracotta", # (various_colors:_minecraft:white_glazed_terracotta,_etc)
        "-": "minecraft:brick_block",
        "-": "minecraft:sandstone",
        "-": "minecraft:purpur_block",
        "-": "minecraft:end_stone",
        "-": "minecraft:prismarine",
        "-": "minecraft:prismarine_bricks",
        "-": "minecraft:dark_prismarine",
        "-": "minecraft:obsidian",
        "-": "minecraft:netherrack",
        "-": "minecraft:nether_bricks",
    },
    "4_wood_and_logs": {
        "-": "minecraft:oak_log",
        "-": "minecraft:birch_log",
        "-": "minecraft:spruce_log",
        "-": "minecraft:jungle_log",
        "-": "minecraft:acacia_log",
        "-": "minecraft:dark_oak_log",
        "-": "minecraft:mangrove_log",
        "-": "minecraft:crimson_stem",
        "-": "minecraft:warped_stem",
        "-": "minecraft:stripped_oak_log",
        "-": "minecraft:stripped_birch_log",
        "-": "minecraft:stripped_spruce_log",
        "-": "minecraft:stripped_jungle_log",
        "-": "minecraft:stripped_acacia_log",
        "-": "minecraft:stripped_dark_oak_log",
        "-": "minecraft:stripped_mangrove_log",
    },
    "5_plant-based_blocks": {
        "-": "minecraft:oak_leaves",
        "-": "minecraft:birch_leaves",
        "-": "minecraft:spruce_leaves",
        "-": "minecraft:jungle_leaves",
        "-": "minecraft:acacia_leaves",
        "-": "minecraft:dark_oak_leaves",
        "-": "minecraft:cactus",
        "-": "minecraft:sugar_cane",
        "-": "minecraft:melon",
        "-": "minecraft:pumpkin",
        "-": "minecraft:bamboo",
        "-": "minecraft:vines",
        "-": "minecraft:lily_pad",
        "-": "minecraft:seagrass",
        "-": "minecraft:kelp",
        "-": "minecraft:poppy",
        "-": "minecraft:dandelion",
        "-": "minecraft:allium",
        "-": "minecraft:blue_orchid",
        "-": "minecraft:red_mushroom",
        "-": "minecraft:brown_mushroom",
    },
    "6_decoration_blocks": {
        "-": "minecraft:bookshelf",
        "-": "minecraft:carpet", # (various_colors:_minecraft:white_carpet,_minecraft:black_carpet,_etc)
        "-": "minecraft:banner", # (customizable;_basic_form:_minecraft:white_banner,_etc)
        "-": "minecraft:painting",
        "-": "minecraft:flower_pot",
        "-": "minecraft:lantern",
        "-": "minecraft:sea_lantern",
        "-": "minecraft:glowstone",
        "-": "minecraft:shroomlight",
        "-": "minecraft:end_rod",
        "-": "minecraft:chiseled_stone_bricks",
        "-": "minecraft:chiseled_sandstone",
    },
    "7_functional_blocks": {
        "-": "minecraft:crafting_table",
        "-": "minecraft:furnace",
        "-": "minecraft:blast_furnace",
        "-": "minecraft:smoker",
        "-": "minecraft:anvil",
        "-": "minecraft:enchanting_table",
        "-": "minecraft:grindstone",
        "-": "minecraft:smithing_table",
        "-": "minecraft:brewing_stand",
        "-": "minecraft:cartography_table",
        "-": "minecraft:loom",
        "-": "minecraft:stonecutter",
        "-": "minecraft:fletching_table",
        "-": "minecraft:barrel",
        "-": "minecraft:cauldron",
        "-": "minecraft:composter",
        "-": "minecraft:campfire",
        "-": "minecraft:lectern",
        "-": "minecraft:beacon",
    },
    "8_utility_blocks": {
        "-": "minecraft:chest",
        "-": "minecraft:trapped_chest",
        "-": "minecraft:ender_chest",
        "-": "minecraft:shulker_box",
        "-": "minecraft:hopper",
        "-": "minecraft:dispenser",
        "-": "minecraft:dropper",
        "-": "minecraft:note_block",
        "-": "minecraft:jukebox",
        "-": "minecraft:observer",
        "-": "minecraft:redstone_repeater",
        "-": "minecraft:redstone_comparator",
        "-": "minecraft:piston",
        "-": "minecraft:sticky_piston",
    },
    "9_redstone_blocks": {
        "-": "minecraft:redstone",
        "-": "minecraft:redstone_block",
        "-": "minecraft:redstone_torch",
        "-": "minecraft:lever",
        "-": "minecraft:stone_button",
        "-": "minecraft:wooden_button",
        "-": "minecraft:stone_pressure_plate",
        "-": "minecraft:wooden_pressure_plate",
        "-": "minecraft:iron_pressure_plate",
        "-": "minecraft:gold_pressure_plate",
        "-": "minecraft:tripwire_hook",
        "-": "minecraft:daylight_detector",
    },
    "10_nether_blocks": {
        "-": "minecraft:nether_wart_block",
        "-": "minecraft:crimson_nylium",
        "-": "minecraft:warped_nylium",
        "-": "minecraft:basalt",
        "-": "minecraft:blackstone",
        "-": "minecraft:soul_sand",
        "-": "minecraft:soul_soil",
        "-": "minecraft:magma_block",
    },
    "11_end_blocks": {
        "-": "minecraft:end_stone",
        "-": "minecraft:purpur_block",
        "-": "minecraft:chorus_plant",
        "-": "minecraft:chorus_flower",
    },
    "12_light_sources": {
        "-": "minecraft:torch",
        "-": "minecraft:lantern",
        "-": "minecraft:glowstone",
        "-": "minecraft:sea_lantern",
        "-": "minecraft:redstone_lamp",
        "-": "minecraft:jack_o_lantern",
        "-": "minecraft:shroomlight",
    },
    "13_miscellaneous": {
        "-": "minecraft:bedrock",
        "-": "minecraft:spawner",
        "-": "minecraft:cobweb",
        "-": "minecraft:scaffolding",
        "-": "minecraft:barrier",
        "-": "minecraft:command_block",
    }
}